### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by gherson** [AceWiki/AceWiki#26]
Any reason not to enable math in AceWiki?  E.g.,

    Pi is 3.14.
    What is Pi * Pi?
    -9.8596

**Comment by gherson** [comment]
Other than the need to swap in a bullet point to replace the minus sign.

**Comment by tkuhn** [comment]
The main reason why this is not supported is that you cannot do this kind of mathematical reasoning with OWL. In general, even simple arithmetics quickly introduce undecidability. So, there is no easy solution to introduce such math expressions in a useful way.

**Comment by gherson** [comment]
Ok.  Can we get a RACE reasoner option?

"I submitted a follow-up paper describing reasoning in arithmetic and non-monotonic reasoning to the workshop CNL 2016. This paper is not yet public." -- nef to attempto mailing list 4/18/16

**Comment by tkuhn** [comment]
> Ok. Can we get a RACE reasoner option?

That'd be possible but not trivial. I have no plans to do it myself :)

You'd have to implement this interface and connect it to RACE:
https://github.com/AceWiki/AceWiki/blob/master/src/ch/uzh/ifi/attempto/acewiki/core/AceWikiReasoner.java

The difficulties are that RACE hasn't been developed so far as a library to be used in other programs, so there might be problems there. And of course it covers a very expressive subset of first-order logic that is not decidable. So, you can expect to encounter cases where answers take a loooong time (read: forever), in particular if you have a reasonably sized knowledge base in the wiki. So, I am not sure whether such kind of powerful reasoning is well-suited for a wiki-style open environment.

**Comment by gherson** [comment]
Re: undecidability, is it possible for a reasoner to do a nice job (better than a timeout) determining when it is looping unprofitably?  If yes, it could quit with an appropriate error message and that'd be better IMO than disallowing risky questions.

**Comment by tkuhn** [comment]
> is it possible for a reasoner to do a nice job (better than a timeout) determining when it is looping unprofitably?

Not really. It's at the core of undecidability that you cannot in general distinguish profitable from unprofitable looping.

> it could quit with an appropriate error message and that'd be better IMO than disallowing risky questions.

It's not just about questions. The knowledge base itself can quickly become too complicated to answer **any** question about it.

**Comment by gherson** [comment]
But a human can do a good job.  Using only its intelligence.

**Comment by tkuhn** [comment]
You mean wrt profitable versus unprofitable looping? Undecidability means that no reasoning can be both 100% correct and 100% complete. Human reasoning is neither 100% correct nor 100% complete (and very slow on top of that). Good automated reasoners are at least 100% correct, but therefore cannot be 100% complete.

**Comment by gherson** [comment]
I appreciate that computer science has this Uncertainty Principle (undecidability) but artificial intelligence is profitable at intelligence questions without being 100%.  It could monitor the reasoner i think.

**Comment by tkuhn** [comment]
Right, I agree, but then you should probably look into machine learning approaches rather than logic reasoners :). The kinds of reasoners we were discussing here (OWL/logic reasoners), are built on the premise that they only make valid deductions (= 100% correct). With this simple premise, all that nasty stuff about undecidability follows. Unless, like OWL, you are very careful to remain in a decidable subset of logic, but then you cannot do much math in it.

**Comment by gherson** [comment]
Fair enough.  The AI could use the reasoner like a human uses a calculator.  But, I will concede the difficulty, and close this for now.
