### ISSUE TITLE
diamond type objection

### ISSUE THREAD

**Issue by gherson** [AceWiki/AceWiki#27]
Of AceWiki\src\ch\uzh\ifi\attempto\acewiki\Wiki.java line 792,

    List<WikiPage> pages = new ArrayList<>();
Intellij IDEA v15.0.2 with JDK 1.8.0_66 says it has error "Diamond types are not supported at this language level".

    List<WikiPage> pages = new ArrayList<WikiPage>();
makes it happy.

(I'll include this in a planned pull request if that's helpful.)

**Comment by Kaljurand** [comment]
The diamond operator was added in Java 7. Maybe we should officially drop support for earlier versions, rather than rewrite the code to be more redundant.

**Comment by gherson** [comment]
Agree (so I won't close yet).

Thanks for the info.  After changing IntelliJ's "project language [level](http://stackoverflow.com/questions/17714584/what-is-project-language-level-in-intellij-idea)" to Java 7, the "error" went away.  No code change necessary.
