### ISSUE TITLE
Chart parser: lambda resolution time grows exponentially with the number of tokens

### ISSUE THREAD

**Issue by amirant** [AceWiki/AceWiki#28]
Attached is a maven project with a very simple grammar with semantic annotations and a unit test that shows how the lambda resolution time grows very quickly with the number of tokens used in the sentence. Running the test we get this output:

=> lambda resolution time: 0 seconds, 11 tokens.
=> lambda resolution time: 2 seconds, 31 tokens.
=> lambda resolution time: 34 seconds, 35 tokens.

and the problem appears with fewer tokens if the grammar is more complex. The chart parser itself seems to perform the same with any number of tokens.

Regards,
Amir.

[helloGrammar.tar.gz](https://github.com/AceWiki/AceWiki/files/349392/helloGrammar.tar.gz)

**Comment by tkuhn** [comment]
Thanks for reporting this. I think I implemented the lambda resolution in a very naive way. It should be possible to improve its performance at lot. I even wrote a TODO note back then, stating that the beta reduction method should be improved: https://github.com/AceWiki/AceWiki/blob/master/src/ch/uzh/ifi/attempto/chartparser/ParseTree.java#L286

I will try to find time to look into this.

**Comment by tkuhn** [comment]
Resolved with commit 92ba9844a4a1c97f5fce5b3005da96cc8cc89cde.
