### ISSUE TITLE
Demo sites not working

### ISSUE THREAD

**Issue by Konard** [AceWiki/AceWiki#29]
http://attempto.ifi.uzh.ch/webapps/acewikigeo/
http://attempto.ifi.uzh.ch/webapps/acewikiattempto/
http://attempto.ifi.uzh.ch/webapps/acewikisandbox/

All links not working.

**Comment by tkuhn** [comment]
AceWiki demos are up again. Thanks for reporting this!

**Comment by Konard** [comment]
Thank you for upping them.

**Comment by Konard** [comment]
Thank you for upping them.

**Comment by lw1990** [comment]
The demos are down again!

**Comment by tkuhn** [comment]
I have just restarted them and now they are up again.

I have also set up another demo instance here: https://acewiki.petapico.org/

I hope that helps
